apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: analytics
type: Opaque
stringData:
  # Superset admin bootstrap credentials (change in your env if needed)
  SUPERSET_ADMIN_USERNAME: admin
  SUPERSET_ADMIN_PASSWORD: admin
  SUPERSET_ADMIN_FIRST_NAME: Admin
  SUPERSET_ADMIN_LAST_NAME: User
  SUPERSET_ADMIN_EMAIL: admin@example.com
  # Flask secret key
  SECRET_KEY: "change_this_in_real_env"
  # SQLAlchemy connection to Postgres in the postgres namespace
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://demo:demo@postgres.postgres.svc.cluster.local:5432/demo_noetl
