apiVersion: v1
kind: Service
metadata:
  name: noetl-gateway
  labels:
    app: noetl-gateway
spec:
  selector:
    app: noetl-gateway
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
