apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.env.routerPort | default "8090" }}
      protocol: TCP
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
