apiVersion: v1
kind: Secret
metadata:
  name: noetl-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: noetl
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}
  NOETL_PASSWORD: {{ .Values.secrets.noetlPassword | b64enc }}
