{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: noetl-ext
  namespace: {{ .Values.namespace }}
  labels:
    app: noetl-server
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - port: {{ .Values.externalService.port }}
      protocol: TCP
      name: http
{{- if .Values.externalService.nodePort }}
      nodePort: {{ .Values.externalService.nodePort }}
{{- end }}
  selector:
    app: noetl-server
{{- end }}
