apiVersion: v1
kind: Service
metadata:
  name: noetl
  namespace: {{ .Values.namespace }}
  labels:
    app: noetl
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: noetl
  selector:
    app: noetl-server
