apiVersion: v1
kind: Service
metadata:
  name: gateway-ui
  namespace: gateway
  labels:
    app: gateway-ui
spec:
  type: NodePort
  selector:
    app: gateway-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
