apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-api
  namespace: noetl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-api
  template:
    metadata:
      labels:
        app: noetl-api
    spec:
      containers:
      - name: noetl-api
        image: ghcr.io/noetl/noetl-api:latest
        ports:
        - containerPort: 8021
        env:
        - name: NATS_URL
          value: "nats://nats.nats.svc.cluster.local:4222"
        - name: MAX_REQUESTS
          value: "1000"
        - name: MAX_CONCURRENCY
          value: "500"
        - name: ENV
          value: "local"
        - name: LOG_LEVEL
          value: "INFO"
