apiVersion: v1
kind: Service
metadata:
  name: noetl-api
  namespace: noetl
spec:
  selector:
    app: noetl-api
  ports:
  - protocol: TCP
    port: 8021
    targetPort: 8021

---
apiVersion: v1
kind: Service
metadata:
  name: noetl-api-ext
  namespace: noetl
spec:
  type: NodePort
  selector:
    app: noetl-api
  ports:
  - nodePort: 30080
    port: 8021
    protocol: TCP
    targetPort: 8021
