apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: noetl
  labels:
    app: jupyterlab
    component: analytics
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30888
