apiVersion: v1
kind: Service
metadata:
  name: ibkr-client-portal
  namespace: ibkr
spec:
  type: NodePort
  selector:
    app: ibkr-client-portal
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
