apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: analytics
  labels:
    app: jupyterlab
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30999
