apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: demo_noetl
  POSTGRES_USER: demo
  POSTGRES_SCHEMA: public
  NOETL_USER: noetl
  NOETL_SCHEMA: noetl
  PGDATA: /var/lib/postgresql/data/pgdata
  # Timezone - Change to America/Chicago or other timezone if needed
  # Note: Changing timezone requires rebuilding postgres image and redeploying
  TZ: UTC
