name: "Build image on Release ⚙️"

# on:
#   release:
#     types: [published]
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build_deploy:
    name: build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    env:
      # IMAGE_TAG: ${{ github.event.release.tag_name }}
      IMAGE_TAG: v0.0.0-ci

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}  

      # # Access must be provided on the package level
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # - name: Get token
      #   id: app-token
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
      #     private-key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}

      # - name: Log in to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: oauth2accesstoken
      #     password: ${{ steps.app-token.outputs.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/noetl/ci/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/noetl/noetl:${{ env.IMAGE_TAG }}

# $REGISTRY/$IMAGE_NAME:latest
